package com.maave.maps2go1.modelo;
// Generated 30/03/2019 02:42:33 PM by Hibernate Tools 4.3.1



/**
 * Comentario generated by hbm2java
 */
public class Comentario  implements java.io.Serializable {


     private int numComentario;
     private String contenido;
     private int likes;
     private int dislikes;
     private int numMarcador;
     private int idUsuario;

    public Comentario() {
    }

    public Comentario(int numComentario, String contenido, int likes, int dislikes, int numMarcador, int idUsuario) {
       this.numComentario = numComentario;
       this.contenido = contenido;
       this.likes = likes;
       this.dislikes = dislikes;
       this.numMarcador = numMarcador;
       this.idUsuario = idUsuario;
    }
   
    public int getNumComentario() {
        return this.numComentario;
    }
    
    public void setNumComentario(int numComentario) {
        this.numComentario = numComentario;
    }
    public String getContenido() {
        return this.contenido;
    }
    
    public void setContenido(String contenido) {
        this.contenido = contenido;
    }
    public int getLikes() {
        return this.likes;
    }
    
    public void setLikes(int likes) {
        this.likes = likes;
    }
    public int getDislikes() {
        return this.dislikes;
    }
    
    public void setDislikes(int dislikes) {
        this.dislikes = dislikes;
    }
    public int getNumMarcador() {
        return this.numMarcador;
    }
    
    public void setNumMarcador(int numMarcador) {
        this.numMarcador = numMarcador;
    }
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }




}


