package com.maave.maps2go1.modelo;
// Generated 30/03/2019 02:42:33 PM by Hibernate Tools 4.3.1



/**
 * Marcador generated by hbm2java
 */
public class Marcador  implements java.io.Serializable {


     private int numMarcador;
     private String descripcion;
     private String datosUtiles;
     private double longitud;
     private double latitud;
     private String tipoTema;

    public Marcador() {
    }

	
    public Marcador(int numMarcador, String descripcion, double longitud, double latitud, String tipoTema) {
        this.numMarcador = numMarcador;
        this.descripcion = descripcion;
        this.longitud = longitud;
        this.latitud = latitud;
        this.tipoTema = tipoTema;
    }
    public Marcador(int numMarcador, String descripcion, String datosUtiles, double longitud, double latitud, String tipoTema) {
       this.numMarcador = numMarcador;
       this.descripcion = descripcion;
       this.datosUtiles = datosUtiles;
       this.longitud = longitud;
       this.latitud = latitud;
       this.tipoTema = tipoTema;
    }
   
    public int getNumMarcador() {
        return this.numMarcador;
    }
    
    public void setNumMarcador(int numMarcador) {
        this.numMarcador = numMarcador;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getDatosUtiles() {
        return this.datosUtiles;
    }
    
    public void setDatosUtiles(String datosUtiles) {
        this.datosUtiles = datosUtiles;
    }
    public double getLongitud() {
        return this.longitud;
    }
    
    public void setLongitud(double longitud) {
        this.longitud = longitud;
    }
    public double getLatitud() {
        return this.latitud;
    }
    
    public void setLatitud(double latitud) {
        this.latitud = latitud;
    }
    public String getTipoTema() {
        return this.tipoTema;
    }
    
    public void setTipoTema(String tipoTema) {
        this.tipoTema = tipoTema;
    }




}


