package com.maave.maps2go1.modelo;
// Generated 30/03/2019 02:42:33 PM by Hibernate Tools 4.3.1



/**
 * Tema generated by hbm2java
 */
public class Tema  implements java.io.Serializable {


     private String tipoTema;
     private String color;
     private int idUsuario;

    public Tema() {
    }

    public Tema(String tipoTema, String color, int idUsuario) {
       this.tipoTema = tipoTema;
       this.color = color;
       this.idUsuario = idUsuario;
    }
   
    public String getTipoTema() {
        return this.tipoTema;
    }
    
    public void setTipoTema(String tipoTema) {
        this.tipoTema = tipoTema;
    }
    public String getColor() {
        return this.color;
    }
    
    public void setColor(String color) {
        this.color = color;
    }
    public int getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(int idUsuario) {
        this.idUsuario = idUsuario;
    }




}


